---
title: "projects"
date: '2018-06-28T00:00:00Z'
header:
  caption: ''
  image: ''
profile: no
reading_time: no
share: no
summary: Here we describe how to add a page to your site.
comments: no
---

## Making Deliberation Work: Testing Theories of Deliberation

In this project, I address three questions concerning the design and implementation of deliberative institutions in the United States. First, how do institutional choices in recruitment affect the pool of willing participants? I argue that people will express greater interest in taking part in deliberation when it is presented in a nonpartisan manner. Using a series of online experiments, I demonstrate that invitations from nonpartisan conveners elicit interest from politically-diverse groups. Second, what factors affect participants' behavior during deliberative sessions? A common critique of deliberative democracy is that it cannot overcome the well-documented biases in people's information processing. I propose a theory based in motivated reasoning, arguing that reason-giving rules in deliberative sessions help to overcome biased directionally-motivated reasoning. Using experimental deliberative sessions varying the reason-giving rules, I find that reason-giving results in higher discourse quality, and decreases opinion polarization. Third, how do structural factors affect spillover effects from deliberative sessions? While it is unreasonable to expect full citizenry participation in any deliberation effort, those who do not participate may experience some of the benefits through their social networks. For this portion of the project, I use post-deliberation discussion network data from the experimental sessions to better understand the multiplier effects from deliberative sessions. Overall, this project addresses underdeveloped areas within the deliberation literature, drawing upon work on participation, information processing, and discussion networks; it also provides a much-needed link to deliberative practitioners who rarely test myriad assumptions when designing and conducting deliberative institutions.
